=== benjaminrosenbaum/biblio-gen/schema/works.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="author" type="AuthorType"/>

<xsd:complexType name="AuthorType" >
  <xsd:sequence>
      <xsd:element name="works" type="WorksType" />
      <xsd:element name="bio" type="xsd:string" minOccurs="0" maxOccurs="1" />
	  <xsd:element name="interview" minOccurs="0" maxOccurs="unbounded" >
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="venue" type="VenueType" />
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>     
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="WorksType">
  <xsd:sequence>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="work" type="WorkType" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="WorkType" mixed="false">   
	<xsd:sequence>
      <xsd:element name="type" >    
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="story"/>
					<xsd:enumeration value="poem"/>
					<xsd:enumeration value="article"/>
					<xsd:enumeration value="book"/>
					<xsd:enumeration value="game"/>
					<xsd:enumeration value="asEditor"/>
				</xsd:restriction>
			</xsd:simpleType>
	  </xsd:element>	  
	  <xsd:element name="title" type="xsd:string" />
	  <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1" />    
	  <xsd:element name="collaborators" minOccurs="0" maxOccurs="1" >
		  <xsd:complexType>
			<xsd:sequence>
			  <xsd:element name="venue" type="VenueType" minOccurs="0" maxOccurs="unbounded"  />
			</xsd:sequence>
		  </xsd:complexType>
	  </xsd:element>      
	  <xsd:element name="url" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="seller" minOccurs="0" maxOccurs="unbounded" >
		  <xsd:complexType>
			<xsd:sequence>
			  <xsd:element name="venue" type="VenueType" />
			</xsd:sequence>
		  </xsd:complexType>
      </xsd:element>  
      <xsd:element name="publication" type="PublicationType" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="adaptation" type="AdaptationType" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="translation" type="TranslationType" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="recognition" type="RecognitionType" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="review" type="ReviewType" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="subcomponents" minOccurs="0" maxOccurs="unbounded" >
		  <xsd:complexType>
			<xsd:sequence>
			  <xsd:element name="venue" type="VenueType" />
			</xsd:sequence>
		  </xsd:complexType>
      </xsd:element>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="PublicationType" >
  <xsd:sequence>
    <xsd:element name="venue" type="VenueType"/>
    <xsd:element name="date" type="xsd:string" minOccurs="0" maxOccurs="1" />
    <xsd:element name="reprint" type="xsd:boolean" />
    <xsd:element name="otherPubInfo" type="xsd:string" minOccurs="0" maxOccurs="1" />  
    <xsd:element name="type" minOccurs="0" maxOccurs="1"  >    
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="website"/>
					<xsd:enumeration value="webExhibit"/>
					<xsd:enumeration value="podcast"/>
					<xsd:enumeration value="paidDownload"/>
				</xsd:restriction>
			</xsd:simpleType>
	  </xsd:element>      
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="AdaptationType" >
  <xsd:sequence>
    <xsd:element name="adaptor" type="xs:string" minOccurs="0" maxOccurs="1" />	 
    <xsd:element name="type" minOccurs="0" maxOccurs="1"  >    
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="film"/>
					<xsd:enumeration value="radioPlay"/>
					<xsd:enumeration value="stageProduction"/>
				</xsd:restriction>
			</xsd:simpleType>
	  </xsd:element>
    <xsd:element name="url" type="xs:string" minOccurs="0" maxOccurs="1" />
    <xsd:element name="adaptationTitle" type="xs:string" minOccurs="0" maxOccurs="1" />
    <xsd:element name="publication" type="PublicationType" minOccurs="0" maxOccurs="unbounded" />   
	<xsd:element name="recognition" type="RecognitionType" minOccurs="0" maxOccurs="unbounded" />	
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="TranslationType" >
  <xsd:sequence>
    <xsd:element name="translator" type="xs:string" minOccurs="0" maxOccurs="1" />
    <xsd:element name="language" type="xs:string"/>
    <xsd:element name="url" type="xs:string" minOccurs="0" maxOccurs="1" />
    <xsd:element name="translatedTitle" type="xs:string" minOccurs="0" maxOccurs="1" />
    <xsd:element name="publication" type="PublicationType" minOccurs="0" maxOccurs="unbounded" />  
	<xsd:element name="recognition" type="RecognitionType" minOccurs="0" maxOccurs="unbounded" />	  
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="RecognitionType" >
  <xsd:sequence>
    <xsd:element name="venue" type="VenueType"/>
    <xsd:element name="type" minOccurs="0" maxOccurs="1"  >    
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="listed"/>
					<xsd:enumeration value="shortlisted"/>
					<xsd:enumeration value="finalist"/>
					<xsd:enumeration value="honorableMention"/>
					<xsd:enumeration value="won"/>
					<xsd:enumeration value="other"/>
				</xsd:restriction>
			</xsd:simpleType>
	  </xsd:element>	
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ReviewType" >
  <xsd:sequence>
    <xsd:element name="venue" type="VenueType"/>
    <xsd:element name="url" minOccurs="0" maxOccurs="1"  />
    <xsd:element name="note" minOccurs="0" maxOccurs="1"  />	
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="VenueType" >
  <xsd:sequence>
    <xsd:element name="name" type="xsd:string" />
    <xsd:element name="url" type="xsd:string" minOccurs="0" maxOccurs="1" />    
  </xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== benjaminrosenbaum/biblio-gen/works/works.xml
<?xml version="1.0" encoding="ISO-8859-1"?><?xml-stylesheet href="works.xsl" type="text/xsl" ?><?jaxfront version=2.80;time=2014-02-26 21:06:41.447;xui=works.xui;xsd=works.xsd;nsMapping=%KEYhttp://www.jaxfront.com/xui%VAL%KEYhttp://www.w3.org/2001/XMLSchema%VALxsd%KEYhttp://www.w3.org/2001/XMLSchema-instance%VALxsi?><author xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="works.xsd">
       <works>
              <work>
                     <type>book</type>
                     <title>The Ant King and Other Stories</title>
                     <description>full-length short story collection</description>
                     <url>http://theantking.com</url>
                     <seller>
                            <venue>
                                   <name>Amazon</name>
                                   <url>http://www.amazon.com/Ant-King-Stories-Benjamin-Rosenbaum/dp/1931520526/benjaminrosenbau/</url>
                            </venue>
                     </seller>
                     <seller>
                            <venue>
                                   <name>Powell's</name>
                                   <url>http://www.powells.com/biblio?isbn=978-1931520522</url>
                            </venue>
                     </seller>
                     <seller>
                            <venue>
                                   <name>Borders</name>
                                   <url>http://www.bordersstores.com/search/title_detail.jsp?id=57604512</url>
                            </venue>
                     </seller>
                     <publication>
                            <venue>
                                   <name>Small Beer Press</name>
                                   <url>http://lcrw.net</url>
                            </venue>
                            <date>August 5, 2008</date>
                            <reprint>false</reprint>
                     </publication>
                     <recognition>
                            <venue>
                                   <name>LA Times 2008 Favorite SF Books</name>
                                   <url>http://www.latimes.com/features/books/la-ca-favoritebooks-sciencefict-2008dec07,0,3049326.story</url>
                            </venue>
                            <type>listed</type>
                     </recognition>
                     <recognition>
                            <venue>
                                   <name>WFMU Top 10+ Books of 2008</name>
                                   <url>http://blog.wfmu.org/freeform/2008/12/inflatable-squi.html</url>
                            </venue>
                            <type>listed</type>
                     </recognition>
                     <review>
                            <venue>
                                   <name>Publisher's Weekly</name>
                            </venue>
                            <url>http://www.publishersweekly.com/article/CA6571633.html#SF/Fantasy/Horror</url>
                            <note>(scroll down a bit)</note>
                     </review>
                     <review>
                            <venue>
                                   <name>Kirkus</name>
                            </venue>
                            <url>http://www.kirkusreviews.com/kirkusreviews/headlines/fiction_display.jsp?vnu_content_id=1003821558</url>
                            <note>"An imaginative debut collection." (subscription required to view)</note>
                     </review>
                     <review>
                            <venue>
                                   <name>Bibliophile Stalker</name>
                            </venue>
                            <url>http://charles-tan.blogspot.com/2008/05/book-review-ant-king-and-other-stories.html</url>
                     </review>
                     <review>
                            <venue>
                                   <name>LA Times</name>
                            </venue>
                            <url>http://www.latimes.com/features/books/la-caw-astral-weeks2-2008nov02,1,5009629.story</url>
                     </review>
                     <review>
                            <venue>
                                   <name>The Washington Post</name>
                            </venue>
                            <url>http://www.washingtonpost.com/wp-dyn/content/article/2008/10/09/AR2008100902537.html?sub=AR</url>
                     </review>
                     <review>
                            <venue>
                                   <name>The Boston Phoenix</name>
                            </venue>
                            <url>http://thephoenix.com/Boston/Arts/66915-Out-of-this-world/</url>
                     </review>
                     <review>
                            <venue>
                                   <name>The Weekly Dig</name>
                            </venue>
                            <url>http://www.weeklydig.com/arts-entertainment/words/200805/perfect-form</url>
                     </review>
                     <review>
                            <venue>
                                   <name>Fantasy Book Spot</name>
                            </venue>
                            <url>http://www.bookspotcentral.com/2008/08/book-review-the-ant-king-and-other-stories/</url>
                     </review>
                     <review>
                            <venue>
                                   <name>SF Revu</name>
                            </venue>
                            <url>http://www.sfrevu.com/php/Review-id.php?id=6787</url>
                     </review>
                     <review>
                            <venue>
                                   <name>The Agony Column</name>
                            </venue>
                            <url>http://www.trashotron.com/agony/news/2008/05-19-08.htm#052208</url>
                     </review>
                     <review>
                            <venue>
                                   <name>Genre-Go-Round</name>
                            </venue>
                            <url>http://genregoroundreviews.blogspot.com/2008/07/ant-king-and-other-stories-benjamin.html</url>
                     </review>
                     <review>
                            <venue>
                                   <name>BoomTron</name>
                                   <url>http://www.boomtron.com</url>
                            </venue>
                            <url>http://www.boomtron.com/2008/08/book-review-the-ant-king-and-other-stories/</url>
                     </review>
              </work>
              <work>
                     <type>story</type>
                     <title>The First Gate of Logic</title>
                     <publication>
                            <venue>
                                   <name>Stories For Chip, ed. Nisi Shawl &amp; Bill Campbell</name>
                                   <url>http://www.amazon.com/Stories-Chip-Tribute-Samuel-Delany/dp/0990319172</url>
                            </venue>
                            <date><i>August 3, 2015</i></date>
                            <reprint>false</reprint>
                     </publication>
              </work>

              <work>
                     <type>article</type>
                     <title>Navigating Masculinity: A Roundtable</title>
                     <collaborators>
                            <venue>
                                   <name>Mary Anne Mohanraj</name>
                            </venue>
                            <venue>
                                   <name>Na'amen Tilahun</name>
                            </venue>
                            <venue>
                                   <name>Elliott Mason</name>
                            </venue>
                            <venue>
                                   <name>Jim C. Hines</name>
                            </venue>
                            <venue>
                                   <name>Jed Hartman</name>
                            </venue>
                            <venue>
                                   <name>David Moles</name>
                            </venue>
                            <venue>
                                   <name>Michael Damian Thomas</name>
                            </venue>
                     </collaborators>
                     <publication>
                            <venue>
                                   <name>The WisCon Chronicles, Vol.9: Intersections and Alliances, ed. Mary Anne Mohanraj</name>
                                   <url>http://www.aqueductpress.com/books/978-1-61976-087-5.php</url>
                            </venue>
                            <date><i>June 1, 2015</i></date>
                            <reprint>false</reprint>
                     </publication>
              </work>
              <work>
                     <type>story</type>
                     <title>Tractate Metim 28a</title>
                     <publication>
                            <venue>
                                   <name>Jews vs. Zombies, ed. Rebecca Levine &amp; Lavie Tidhar</name>
                                   <url>http://www.amazon.com/Jews-vs-Zombies-Rebecca-Levene-ebook/dp/B00TQT6L9K/</url>
                            </venue>
                            <date><i>March 19, 2015</i></date>
                            <reprint>false</reprint>
                     </publication>
              </work>
              <work>
                     <type>story</type>
                     <title>Fift &amp; Shria</title>
                     <publication>
                            <venue>
                                   <name>Solaris Rising 3, ed. Ian Whates.</name>
